### PR TITLE
updates BasePlant to avoid invoking LazyProperties of defaults when using variation or userOverrides

### PR DESCRIPTION
**Pull request by pirvudoru**

### CODE REVIEW

**Comment by pirvudoru** [comment]
@jbrechtel Hello. Is there any you do review/merge/publish nuget for this PR ?
Thanks!

**Comment by jbrechtel** [comment]
Hi @pirvudoru, sorry for the delay on this. I don't have an issue with merging the changes in but I can't give it an effective review because I've been away from .NET for a really long time now.

Would you be interested in taking ownership of the project?

**Comment by pirvudoru** [comment]
Hello, 
I would be happy to do that. Will you be able to provide nuget credentials also ?

Thanks!

**Comment by jbrechtel** [comment]
I can add you as an owner on NuGet. What's your NuGet username?

**Comment by pirvudoru** [comment]
I just created a personal account. "pirvudoru" is the username. 
Thanks!

**Comment by jbrechtel** [comment]
Looks like it needs you to verify your email before I can make you an owner.

**Comment by pirvudoru** [comment]
Done. Had to manually request a validation email :-1:

**Pull request merged**
